### ISSUE TITLE
Pretty print JSON output

### ISSUE THREAD

**Issue by gwcary** [sassoftware/unravl#22]
It would be a lot easier to read the output if the JSON was indented.  This could be done pretty easily by adding this section in the ApiCall class:

                    if(isJson(headers))
                    {
                        ObjectMapper mapper = new ObjectMapper();
                        mapper.enable(SerializationFeature.INDENT_OUTPUT);
                        Object json = mapper.readValue(bytes.toString(), Object.class);
                        String indented = mapper.writeValueAsString(json);
                        System.out.println(indented);
                    }
                    else
                        // TODO: pretty print XML
                        bytes.writeTo(System.out);

And this utility method:

    private boolean isJson(Header[] headers)
    {
        for(Header header : headers)
        {
            if(header.getName().equals("Content-Type") &&
               header.getValue().contains("json"))
            {
                return true;
            }
        }
        return false;
    }

**Comment by DavidBiesack** [comment]
See pull request https://github.com/sassoftware/unravl/pull/23

**Comment by DavidBiesack** [comment]
merged PR #23
