### ISSUE TITLE
logging options when running through JUnitWrapper

### ISSUE THREAD

**Issue by wongdk** [sassoftware/unravl#51]
Is there a way to change the logging settings for unravl tests run through JUnit?  One thing I noticed is that when a groovy assert fails, the log has something like this:

2015-12-22 14:36:14,441 Script UnRAVL:[now the transformations list should be empty again GET {HOST}/transformation/transformations], returned false

where the variables in the URI aren't expanded, and the error says "returned false" but doesn't say which assertion failed.  In contrast, when a http status assert fails, the log message is more descriptive. ("Actual HTTP status code 200 did not match the expected status, 404 while running UnRAVL script" followed by the name of the test.)

One possibility is something like exceptions in Spock, where the assert that failed is included in the exception message.  Or, is there a way to specify logging options for tests called through JUnitWrapper?  I found the doc for logging options at https://github.com/sassoftware/unravl/blob/master/doc/Reference.md#logging, but don't know how to pass those into the JUnit calls.

thanks!

**Comment by DavidBiesack** [comment]
I added additional logging to print the assertion element that failed.  For example:

```

2015-12-25 21:51:32,120 Groovy script returned false: UnRAVL:[uses implicit template <no method> <no url>] while running UnRAVL script uses implicit template
2015-12-25 21:51:32,120 Failed assertion: {"groovy":"count < 3"}
```

this was fixed in pull request #52
