### ISSUE TITLE
Perform substitution in names for body and JSON objects in "env"

### ISSUE THREAD

**Issue by keganc** [sassoftware/unravl#61]
Per our email  you replied:
UnRAVL only performs substitution in values, not in names, when processing embedded JSON (either for the body or for JSON objects in "env". I did not anticipate any use cases where the names of JSON values would require variable substitution.

In my test case I'm using IntelliJ which calls a Junit test that calls the JSON  
I define
 "env" : {

 "str250":"B12345678901234567890123456789012345678901234567890123456789
 0123456789012345678901234567890123456789012345678901234567890123456789
 0123456789012345678901234567890123456789012345678901234567890123456789
 01234567890123456789012345678901234567890123456789",
  },

 Then I try to pass in str250 to a map object in the json body "body" : 
 {
       "json" : {
       "properties":{"{str250}":"value1"}
       }
 },
But the key gets set to the literal {str250}.  If I hardcode the string in key of the Map it works fine.  Interestingly if I pass str250 to the value in the map it works.

**Comment by DavidBiesack** [comment]
Fixed with PR #62
