### ISSUE TITLE
The UnRAVL script cannot handle the space in "C:\Program Files\...".  

### ISSUE THREAD

**Issue by applesand** [sassoftware/unravl#81]
> c:\unravl-1.2.1\bin>unravl
> Files\Java\jdk1.8.0_60] was unexpected at this time.
> The UnRAVL script cannot handle the space in "C:\Program Files...".  
> (entered by Beth Lohela)

**Comment by DavidBiesack** [comment]
In the interim, if Java is in your path, you should be able to run by unsetting JAVA_HOME before running unravl.bat

**Comment by DavidBiesack** [comment]
This has been fixed via pull request #91.
It is not in a release build yet.
