### ISSUE TITLE
Add variable substitution for all JSON types 

### ISSUE THREAD

**Issue by mikeycamp** [sassoftware/unravl#98]
unravl currently only substitution of string values

```
{ "name": "{var}" }
```

with a passed in number value of 5 would result in

```
{"name":"5"}
```
Rather than ``{"name":5}`` the actual JSON number value

We would like to support all the JSON types : array, null, number, boolean for substitution

I spoke with @DavidBiesack about this and we talked about doing substitution based possibly on a namespace convention. It ain't exactly pretty and is a little verbose but is explicit and wouldn't involve data collisions with existing JSON.
```
{"name": { "unravl:number": "var" } }
// Where var is 5 the resulting JSON object would be
{"name": 5}
```

There may be a better less verbose syntax, but this would certainly not involve collisions. Another proposal could be.

**Comment by mikeycamp** [comment]
Adding an additional ``unravl:any`` type would all for heterogeneous data types.

**Comment by DavidBiesack** [comment]
... such that: 
```
{"name": { "unravl:any": "x" } }
```
would use the current type of var. if `x` is a `Number` `5` (or a `JsonNumber`) it resolves to
```
{ "name" : 5}
```
if `x` is an array it resolves to
```
{ "name" : [ ... ]}
```
This avoids the nastiness of the runtime type of the variable not matching or being coercable into the unravl:number or unravl:boolean or other type notation.

Other options for the "keyword"
```
{"name": { "$unravlValue": "x" } }
{"name": { "unravl:val": "x" } }
```

Another option is to *not* use a wrapper object but to just extend the `{var}` notation such as
```
{"name": "{!varName!}"}
```
or some other notation (Mike mentioned `@` as in `"{@x@}"`; a colon `:` is also tidy as in `"{:x:}"`). Note that such notation is not likely to appear in content unrelated to UnRAVL (request/response bodies), even less likely than the current `"{var}"` notation. I think the notation is probably worth doing and we could provide a *no-evaluate* escape mechanism (TBD).

Note also that if the value of var is a Java/Groovy closure (or Java Script function), UnRAVL could *evaluate* that closure and insert the value back.
 
This could also be extended to support arbitrary Groovy/JavaScript expressions:
```
"{!(list.indexOf(searchItem))!}"
```

**Comment by mikeycamp** [comment]
I do think that is nice, but let's go with object first for less risk `{"unravl:val" : "x"}` it doesn't preclude the other syntax in the future. This one could additionally support the evaluations you are speaking to down the road if needed.

**Comment by OksanaKoziaryk** [comment]
After some discussion we decided to go with the following notation for the actual value replacement `"{@varName@}"`. For example,
{
"env" : { "API_ROOT": "http://www.httpbin.org",
"intvalue": 1
}
"body" : {"int": "{@intvalue@}"
}
}
This will result with the request body containing the actual JSON number value "int": 1 with no embedding into a string.

More information can be found in the [Reference](https://github.com/OksanaKoziaryk/unravl/blob/master/doc/Reference.md#variable-substitution).
